name: Deploy To S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        # github 라이브러리 checkout 사용
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: AWS Resource에 접근할 수 있게 AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 전체 삭제
        # 250528-facebook-web : S3에서의 배포명
        run: aws s3 rm --recursive s3://250528-facebook-web

      - name: S3에 빌드된 파일 업로드하기
        run: aws s3 cp ./dist s3://250528-facebook-web/ --recursive

      - name: CloudFront 캐시 무효화
        # --distribution-id 배포ID
        run: ws cloudfront create-invalidation --distribution-id E233UE5GOZVBDT --paths "/*"
